Table USERS {
    ID varchar [pk]
    FIRST_NAME varchar [not null]
    LAST_NAME varchar [not null]
    DOB date [not null]
    ADDRESS varchar [not null]
    MOBILE varchar [not null]
    CITY_CODE varchar [not null]
    EMAIL varchar [not null]
    PASSWORD varchar [not null]
    REGISTERED date [default: `sysdate`]
    TYPE varchar [default: 'USER', not null]
    PROFILE_IMAGE varchar [default: 'https://placehold.co/600x400']
}

Table QA_OFFICER {
    ID varchar [pk]
    USER_ID varchar [ref: > USERS.ID]
    ACADEMIC_QUALIFICATION varchar [not null]
    APPROVED int [default: 0, note: "CHECK (APPROVED IN (0, 1))"]
    CV_LINK varchar [not null]
    DATE_OF_JOINING date [default: `sysdate`]
}

Table CHEF {
    ID varchar [pk]
    CHEF_NAME varchar [unique, not null]
    USER_ID varchar [ref: > USERS.ID]
    SPECIALITY varchar [not null]
    EXPERIENCE int [default: 0]
    STATUS varchar [default: 'ACTIVE', not null]
}

Table KITCHEN {
    ID varchar [pk]
    NAME varchar [not null]
    ADDRESS varchar [not null]
    CITY_NAME varchar [not null]
    CHEF_ID varchar [ref: > CHEF.ID]
    APPROVED int [default: 0, note: "CHECK (APPROVED IN (0, 1))"]
}

Table KITCHEN_IMAGES {
    ID varchar [pk]
    KITCHEN_ID varchar [ref: > KITCHEN.ID]
    IMAGE varchar [default: 'https://placehold.co/600x400']
    DATE_ADDED date [default: `sysdate`]
}

Table CERTIFICATION {
    ID varchar [pk]
    CHEF_ID varchar [ref: > CHEF.ID]
    CERTIFICATION varchar [unique, not null]
    ISSUE_DATE date [not null]
    EXPIRY_DATE date
    LINK varchar [unique, not null]
    CERTIFICATE_IMAGE varchar [default: 'https://placehold.co/600x400']
}

Table CATEGORY {
    ID varchar [pk]
    KITCHEN_ID varchar [ref: > KITCHEN.ID]
    NAME varchar [not null]
    DESCRIPTION varchar [not null]
    CATEGORY_IMAGE varchar [default: 'https://placehold.co/600x400']
}

Table FOOD {
    ID varchar [pk]
    NAME varchar [not null]
    DESCRIPTION varchar [not null]
    PRICE int [not null]
    RATING int [default: 0]
    CATEGORY_ID varchar [ref: > CATEGORY.ID]
    FOOD_IMAGE varchar [default: 'https://placehold.co/600x400']
}

Table INGREDIENT {
    ID varchar [pk]
    FOOD_ID varchar [ref: > FOOD.ID]
    NAME varchar [not null]
    QUANTITY int [not null]
    CALORIES int [not null]
}

Table ORDERS {
    ID varchar [pk]
    USER_ID varchar [ref: > USERS.ID]
    TOTAL int [default: 0]
    DATE_ADDED date [default: `sysdate`]
    DATE_PREPARED date
    DATE_SHIPPED date
    DATE_DELIVERED date
    SHIPPING_ADD varchar [not null]
    SHIPPING_PHONE varchar [not null]
    SHIPPING_NAME varchar [not null]
    STATUS varchar [default: 'PAID', not null]
}

Table CART {
    ID varchar [pk]
    USER_ID varchar [ref: > USERS.ID]
    FOOD_ID varchar [ref: > FOOD.ID]
    QUANTITY int [not null]
    DATE_ADDED date [default: `sysdate`]
    DELETED int [default: 0, note: "CHECK (DELETED IN (0, 1))"]
    DELETED_ID varchar [ref: > ORDERS.ID]
}

Table DELIVERY_PARTNER {
    ID varchar [pk]
    USER_ID varchar [ref: > USERS.ID]
    LICENSE varchar [not null]
    VEHICLE varchar [not null]
    VERIFIED int [default: 0, note: "CHECK (VERIFIED IN (0, 1))"]
}

Table CONVERSATIONS {
    CONVERSATION_ID varchar [pk]
    USER_ID varchar [ref: > USERS.ID]
    DELIVERY_PARTNER_ID varchar [ref: > USERS.ID]
}

Table MESSAGES {
    MESSAGE_ID varchar [pk]
    CONVERSATION_ID varchar [ref: > CONVERSATIONS.CONVERSATION_ID]
    SENDER_ID varchar [ref: > USERS.ID]
    MESSAGE varchar [not null]
    DATE_ADDED date [default: `sysdate`]
}

Table ACTIVE_DELIVERY {
    ID varchar [pk]
    ORDER_ID varchar [ref: > ORDERS.ID]
    DELIVERY_PARTNER_ID varchar [ref: > USERS.ID]
    STATUS varchar [default: 'PENDING', not null]
}

Table FOOD_RATING {
    ID varchar [pk]
    FOOD_ID varchar [ref: > FOOD.ID]
    USER_ID varchar [ref: > USERS.ID]
    RATING int [default: 0]
    REVIEW varchar [default: '']
    DATE_ADDED date [default: `sysdate`]
}

Table DELIVERY_COMMISION {
    DELIVERY_PARTNER_ID varchar [ref: > DELIVERY_PARTNER.ID]
    AMOUNT int [default: 0.15]
}

Table CHEF_COMMISION {
    CHEF_ID varchar [ref: > CHEF.ID]
    AMOUNT int [default: 0.8]
}

Table LOGS {
    ID varchar [pk]
    LOG_TIMESTAMP date [default: `sysdate`]
    TYPE varchar [not null]
    MESSAGE varchar [not null]
    STATUS varchar [default: 'INFO', not null]
}

Table REPORT_FOOD {
    ID varchar [pk]
    FOOD_ID varchar [ref: > FOOD.ID]
    USER_ID varchar [ref: > USERS.ID]
    REASON varchar [not null]
    STATUS varchar [default: 'PENDING', not null]
    DATE_ADDED date [default: `sysdate`]
}

Ref: CHEF.USER_ID > USERS.ID
Ref: KITCHEN.CHEF_ID > CHEF.ID
Ref: KITCHEN_IMAGES.KITCHEN_ID > KITCHEN.ID
Ref: CERTIFICATION.CHEF_ID > CHEF.ID
Ref: CATEGORY.KITCHEN_ID > KITCHEN.ID
Ref: FOOD.CATEGORY_ID > CATEGORY.ID
Ref: INGREDIENT.FOOD_ID > FOOD.ID
Ref: ORDERS.USER_ID > USERS.ID
Ref: CART.USER_ID > USERS.ID
Ref: CART.FOOD_ID > FOOD.ID
Ref: CART.DELETED_ID > ORDERS.ID
Ref: DELIVERY_PARTNER.USER_ID > USERS.ID
Ref: CONVERSATIONS.USER_ID > USERS.ID
Ref: CONVERSATIONS.DELIVERY_PARTNER_ID > USERS.ID
Ref: MESSAGES.CONVERSATION_ID > CONVERSATIONS.CONVERSATION_ID
Ref: MESSAGES.SENDER_ID > USERS.ID
Ref: ACTIVE_DELIVERY.ORDER_ID > ORDERS.ID
Ref: ACTIVE_DELIVERY.DELIVERY_PARTNER_ID > USERS.ID
Ref: FOOD_RATING.FOOD_ID > FOOD.ID
Ref: FOOD_RATING.USER_ID > USERS.ID
Ref: DELIVERY_COMMISION.DELIVERY_PARTNER_ID > DELIVERY_PARTNER.ID
Ref: CHEF_COMMISION.CHEF_ID > CHEF.ID
Ref: REPORT_FOOD.FOOD_ID > FOOD.ID
Ref: REPORT_FOOD.USER_ID > USERS.ID
